# Generated by Django 5.2.13 on 2026-05-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('referrer', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Waitlist entry',
                'verbose_name_plural': 'Waitlist entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
